#!/bin/sh

printf "This is a way to clean the sourcedest directory.\n It will print a load of \"Unknown command.\" warnings \n... don't worry.\n"

export myBuildDoNotCallMainFunction=1
export myBuildHome="$1"
fromTheDir="$PWD/sourcedest"
intoDir="$PWD/intoDir"
export myBuildSourceDest="${myBuildHome}/sourcedest"
export myBuildHelpersDir="${myBuildHome}/helpers"

#buildSELinux.sh
. "${myBuildHome}"/myBuilds/libcap.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libsepol/libsepol.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libselinux/libselinux.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"

#buildtoolchain.sh
cp -a "${fromTheDir}/linux-deblob" "${intoDir}/linux-deblob"
. "${myBuildHome}"/myBuilds/binutils/binutils.myBuild "" "" ""
printf "Copying ...\n"
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/mingw64/mingw64.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gcc/gcccross.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
cp -a "${fromTheDir}/gcc-prerequisites" "${intoDir}/gcc-prerequisites"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/glibc.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/zlib.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"

#buildbase.sh
. "${myBuildHome}"/myBuilds/busybox/busybox.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/busybox-w32.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/autoconf.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
cp -a "${fromTheDir}/perl" "${intoDir}/perl"
. "${myBuildHome}"/myBuilds/automake.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/iconv.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gettext.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/make/make.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/elfutils.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/texinfo.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/bc.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/openssl.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/kmod.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gawk.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/bison.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/m4/m4.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"

#build wayland
. "${myBuildHome}"/myBuilds/pkg-config.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libffi.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libtool.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/expat.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxml2/libxml2.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/wayland/wayland.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/wayland-protocols.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/pixman.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/pciaccess.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libdrm.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xorgproto.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xtrans.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/pthread-stubs.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxau.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxdmcp.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xcb-proto.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxcb/libxcb.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libX11/libx11.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/python.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/python-setup-tools.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/python-mako.myBuild "" "" "" get
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/flex.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxext.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxfixes.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxdamage.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxshmfence.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxxf86vm.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xrender.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xrandr.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/re2c.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/ninja/ninja.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/meson.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/mesa.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/fontenc.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/freetype.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xfont.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xkbfile.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libpng.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/harfbuzz/harfbuzz.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/glib.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/util-macros.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libepoxy.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xorg-server-wayland.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxkbcommon.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gperf.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/eudev.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/mtdev.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libevdev.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/pcre.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gudev.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/wacom.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/atk.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/fontconfig.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/fribidi.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/cairo/cairo.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/pango.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxml2-python.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/itstool.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/shared-mime-info.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gdk-pixbuf.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxi.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/dbus.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxtst.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/at-spi2-core.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/at-spi2-atk.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/gtk3.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/check.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libinput.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libwebp.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/elogind.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/libxcursor.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/lcms.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/weston.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xkeyboard-config.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"
. "${myBuildHome}"/myBuilds/xkbcomp.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"


#build wine
. "${myBuildHome}"/myBuilds/wine.myBuild "" "" ""
cp -a "${fromTheDir}/${filename}${extension}" "${intoDir}/${filename}${extension}"
printf "Copying ...\n"